[package]
name = "attr_deserialize"
version = "0.1.0"
authors = ["Ted Driggs <ted.driggs@outlook.com>"]
repository = "https://github.com/TedDriggs/attr_deserialize"
description = """
A proc-macro library for reading attributes into structs when
implementing custom derives.
"""
license = "MIT"

[dependencies]
attr_deserialize_core = { version = "=0.1.0", path = "core" }
attr_deserialize_macro = { version = "=0.1.0", path = "macro" }

[workspace]
members = ["macro", "core"]