[package]
name = "darling"
version = "0.1.0"
authors = ["Ted Driggs <ted.driggs@outlook.com>"]
repository = "https://github.com/TedDriggs/darling"
documentation = "https://docs.rs/darling/0.1.0"
description = """
A proc-macro library for reading attributes into structs when
implementing custom derives.
"""
license = "MIT"
readme = "README.md"

[dependencies]
darling_core = { version = "=0.1.0", path = "core" }
darling_macro = { version = "=0.1.0", path = "macro" }

[dev-dependencies]
syn = "0.11"

[workspace]
members = ["macro", "core"]