[package]
name = "darling_macro"
version = "0.1.2"
authors = ["Ted Driggs <ted.driggs@outlook.com>"]
repository = "https://github.com/TedDriggs/darling"
description = """
Internal support for a proc-macro library for reading attributes into structs when
implementing custom derives. Use https://crates.io/crates/darling in your code.
"""
license = "MIT"

[lib]
proc-macro = true

[dependencies]
quote = "0.3.8"
syn = "0.11.11"
darling_core = { version = "=0.1.2", path = "../core" }