[package]
name = "darling_macro"
version = "0.1.1"
authors = ["Ted Driggs <ted.driggs@outlook.com>"]
repository = "https://github.com/TedDriggs/darling"
description = """
A proc-macro library for reading attributes into structs when
implementing custom derives.
"""
license = "MIT"

[lib]
proc-macro = true

[dependencies]
quote = "0.3.8"
syn = "0.11.11"
darling_core = { version = "=0.1.1", path = "../core" }