[package]
name = "darling_core"
version = "0.1.1"
authors = ["Ted Driggs <ted.driggs@outlook.com>"]
repository = "https://github.com/TedDriggs/darling"
description = """
Helper crate for proc-macro library for reading attributes into structs when
implementing custom derives. Use `darling` to get library functionality.
"""
license = "MIT"

[features]
# temporary hack to make Racer autocomplete work; it requires a 3-part version
# number and doesn't allow for any feature declarations.
default = ["syn/full"]

[dependencies]
ident_case = "1.0.0"
lazy_static = "0.2.8"
syn = "0.11.11"
quote = "0.3.12"