[package]
name = "darling_core"
version = "0.1.0"
authors = ["Ted Driggs <ted.driggs@outlook.com>"]

[features]
# temporary hack to make Racer autocomplete work; it requires a 3-part version
# number and doesn't allow for any feature declarations.
default = ["syn/full"]

[dependencies]
ident_case = "1.0.0"
lazy_static = "0.2.8"
syn = "0.11.11"
quote = "0.3.12"